- name: install packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - python-docker

- name: install and configure docker
  command: ./startup.sh -s
  args:
    chdir: "{{ workdir }}"
  become: true

- name: build image
  command: ./build.sh -b "{{ sandbox_branch }}" -i "{{ image_name }}" "{{ image_tag }}"
  args:
    chdir: "{{ workdir }}/container"
  become: true

