- name: set variables
  set_fact:
    container_tag: "{{ zuul.change }}-{{ zuul.patchset }}-{{ zuul.buildset[0:9] }}"

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - python-docker

- name: install and configure docker
  command: ./startup.sh -s
  args:
    chdir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-dev-env"
  become: true

- name: build image
  command: ./build.sh -b {{ zuul.branch }} {{ container_tag }}
  args:
    chdir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-dev-env/container"
  become: true

- name: startup
  command: ./startup.sh -t {{ container_tag }}
  args:
    chdir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-dev-env"
  become: true

- name: show running containers
  command: docker ps
  become: true

- name: Test contrail-dev-env
  include: docker_exec.yaml
  with_items:
    - chdir: /root/contrail
      command: repo sync -j $(nproc) --no-clone-bundle -q

    - chdir: /root/contrail-dev-env
      command: make setup

    - chdir: /root/contrail-dev-env
      command: make dep

    - chdir: /root/contrail-dev-env
      command: make list

    - chdir: /root/contrail-dev-env
      command: make list-containers

    - chdir: /root/contrail-dev-env
      command: make rpm

    - chdir: /root/contrail-dev-env
      command: make containers

    - name: list built packages
      chdir: /root/contrail/RPMS
      command: ls -la *

    - chdir: /root/contrail-dev-env
      command: make clean

- name: cleanup
  command: ./cleanup.sh -v
  args:
    chdir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-dev-env"
  become: true
