- name: Checkout CI jobs repos
  git:
    repo: "https://github.com/{{ item.user }}/{{ item.reponame }}"
    dest: "{{ workdir }}/code/{{ item.reponame }}"
    version: master
  with_items:
    - { user: 'codilime', reponame: 'contrail-project-config' }
    - { user: 'codilime', reponame: 'zuul-jobs' }

