- name: startup
  command: ./startup.sh -i "{{ image_name }}" -t "{{ image_tag }}"
  args:
    chdir: "{{ workdir }}"
  become: true

- name: show running containers
  command: docker ps
  become: true

# For commands below, default chdir is /root/contrail-dev-env
- name: Test contrail-dev-env
  include: docker_exec.yaml
  with_items:
    - chdir: /root/contrail
      command: repo sync -j $(nproc) --no-clone-bundle -q

    - command: make setup

    - command: make fetch_packages

    - command: make dep

    - command: make list

    - command: make list-containers

    - command: make rpm

    - command: make containers

    - name: list built packages
      chdir: /root/contrail/RPMS
      command: ls -la *

    - command: make clean

- name: cleanup
  command: ./cleanup.sh -v
  args:
    chdir: "{{ workdir }}"
  become: true
